/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_spsw_jniprovider_GenericWinSerialPortSocket_FdCleaner */

#ifndef _Included_de_ibapl_spsw_jniprovider_GenericWinSerialPortSocket_FdCleaner
#define _Included_de_ibapl_spsw_jniprovider_GenericWinSerialPortSocket_FdCleaner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_spsw_jniprovider_GenericWinSerialPortSocket_FdCleaner
 * Method:    closeFd
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_GenericWinSerialPortSocket_00024FdCleaner_closeFd
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
