/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_spsw_jniprovider_AbstractSerialPortSocket */

#ifndef _Included_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
#define _Included_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_0_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_0_BPS 1L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_50_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_50_BPS 2L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_75_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_75_BPS 3L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_110_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_110_BPS 4L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_134_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_134_BPS 5L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_150_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_150_BPS 6L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_200_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_200_BPS 7L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_300_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_300_BPS 8L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_600_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_600_BPS 9L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_1200_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_1200_BPS 10L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_1800_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_1800_BPS 11L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_2400_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_2400_BPS 12L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_4800_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_4800_BPS 13L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_9600_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_9600_BPS 14L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_19200_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_19200_BPS 15L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_38400_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_38400_BPS 16L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_57600_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_57600_BPS 17L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_115200_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_115200_BPS 18L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_230400_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_230400_BPS 19L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_460800_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_460800_BPS 20L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_500000_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_500000_BPS 21L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_576000_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_576000_BPS 22L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_921600_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_921600_BPS 23L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_1000000_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_1000000_BPS 24L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_1152000_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_1152000_BPS 25L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_1500000_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_1500000_BPS 26L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_2000000_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_2000000_BPS 27L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_2500000_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_2500000_BPS 28L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_3000000_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_3000000_BPS 29L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_3500000_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_3500000_BPS 30L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_4000000_BPS
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_4000000_BPS 31L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_MASK
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_SPEED_MASK 255L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_DATA_BITS_DB5
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_DATA_BITS_DB5 4096L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_DATA_BITS_DB6
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_DATA_BITS_DB6 8192L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_DATA_BITS_DB7
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_DATA_BITS_DB7 12288L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_DATA_BITS_DB8
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_DATA_BITS_DB8 16384L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_DATA_BITS_MASK
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_DATA_BITS_MASK 61440L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_NONE
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_NONE 65536L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_RTS_CTS_IN
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_RTS_CTS_IN 1048576L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_RTS_CTS_OUT
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_RTS_CTS_OUT 2097152L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_XON_XOFF_IN
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_XON_XOFF_IN 4194304L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_XON_XOFF_OUT
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_XON_XOFF_OUT 8388608L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_MASK
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_FLOW_CONTROL_MASK 16711680L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_STOP_BITS_1
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_STOP_BITS_1 16777216L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_STOP_BITS_1_5
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_STOP_BITS_1_5 33554432L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_STOP_BITS_2
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_STOP_BITS_2 50331648L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_STOP_BITS_MASK
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_STOP_BITS_MASK 251658240L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_NONE
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_NONE 268435456L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_ODD
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_ODD 536870912L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_EVEN
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_EVEN 805306368L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_MARK
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_MARK 1073741824L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_SPACE
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_SPACE 1342177280L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_MASK
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_PARITY_MASK -268435456L
#undef de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_NO_PARAMS_TO_SET
#define de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_NO_PARAMS_TO_SET 0L
/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    read_ArgsOK
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_read_1ArgsOK
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    readBytes
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_readBytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    write_ArgsOK
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_write_1ArgsOK
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    writeBytes
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_writeBytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    readBytes_ArgsOK
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_readBytes_1ArgsOK
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    readSingle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_readSingle
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    sendBreak0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_sendBreak0
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    setBreak0
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_setBreak0
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    getXOFFChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_getXOFFChar
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    getXONChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_getXONChar
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    isCTS
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_isCTS
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    isDSR
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_isDSR
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    isDCD
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_isDCD
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    isRI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_isRI
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    getParameters
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_getParameters
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    getInBufferBytesCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_getInBufferBytesCount
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    getOutBufferBytesCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_getOutBufferBytesCount
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    setDTR
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_setDTR
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    setParameters
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_setParameters
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    setXOFFChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_setXOFFChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    setXONChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_setXONChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    writeBytes_ParamsOK
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_writeBytes_1ParamsOK
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    writeSingle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_writeSingle
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_spsw_jniprovider_AbstractSerialPortSocket
 * Method:    setRTS
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_AbstractSerialPortSocket_setRTS
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
