/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_spsw_jniprovider_GenericTermiosSerialPortSocket_FdCleaner */

#ifndef _Included_de_ibapl_spsw_jniprovider_GenericTermiosSerialPortSocket_FdCleaner
#define _Included_de_ibapl_spsw_jniprovider_GenericTermiosSerialPortSocket_FdCleaner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_spsw_jniprovider_GenericTermiosSerialPortSocket_FdCleaner
 * Method:    closeFds
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_spsw_jniprovider_GenericTermiosSerialPortSocket_00024FdCleaner_closeFds
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
